/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    ContextMenu: typeof import('primevue/contextmenu')['default']
    Datatable: typeof import('./src/components/Datatable.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    Select: typeof import('primevue/select')['default']
    Slider: typeof import('primevue/slider')['default']
    Tag: typeof import('primevue/tag')['default']
    Test: typeof import('./src/components/test.vue')['default']
  }
}
